[build]
  base = "/"
  publish = "public/"
  command = "yarn build"
  functions = "functions/"
  environment = { YARN_VERSION = "1.22.10" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200